server:
  port: 8701
spring:
  profiles:
    active: common, plus
  application:
    name: service-app

logging:
  level:
    cn.zm: debug

global:
  config:
    host: http://localhost:8000/
    services:
      - {service: 股票数据次新股, url: stock_zh_a_new}
      - {service: 消费者信心指数, url: macro_china_xfzxx}
      - {service: 基金基本信息, url: fund_em_fund_name, param: null}
      - {service: 开放式基金-历史数据, url: fund_em_open_fund_info, param1: fund="710001"; 需要基金代码, 可以通过调用 fund_em_open_fund_daily 获取, parame2: indicator="单位净值走势"; 参见 fund_em_open_fund_info 参数一览表}

# eureka
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8700/eureka/
